/**
 * Generated by Scrooge
 *   version: 4.1.0
 *   rev: 87b84f89477a4737c8d57580a1e8bdaeac529b19
 *   built at: 20150928-114741
 */
package com.itiancai.passport.thrift

import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob, ThriftException, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo,
  ThriftStructMetaData, ThriftUtil}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import java.util.Arrays
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}

/**
* 用户登录信息
**/
object UserLogin extends ThriftStructCodec3[UserLogin] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("UserLogin")
  val CredentialField = new TField("credential", TType.STRING, 1)
  val CredentialFieldManifest = implicitly[Manifest[String]]
  val PasswordField = new TField("password", TType.STRING, 2)
  val PasswordFieldManifest = implicitly[Manifest[String]]
  val SourceField = new TField("source", TType.ENUM, 3)
  val SourceFieldI32 = new TField("source", TType.I32, 3)
  val SourceFieldManifest = implicitly[Manifest[com.itiancai.passport.thrift.Source]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      CredentialField,
      false,
      true,
      CredentialFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      PasswordField,
      false,
      true,
      PasswordFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      SourceField,
      false,
      true,
      SourceFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: UserLogin): Unit = {
    if (_item.credential == null) throw new TProtocolException("Required field credential cannot be null")
    if (_item.password == null) throw new TProtocolException("Required field password cannot be null")
    if (_item.source == null) throw new TProtocolException("Required field source cannot be null")
  }

  def withoutPassthroughFields(original: UserLogin): UserLogin =
    new Immutable(
      credential =
        {
          val field = original.credential
          field
        },
      password =
        {
          val field = original.password
          field
        },
      source =
        {
          val field = original.source
          field
        }
    )

  override def encode(_item: UserLogin, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }

  private[this] def lazyDecode(_iprot: LazyTProtocol): UserLogin = {

    var credentialOffset: Int = -1
    var _got_credential = false
    var passwordOffset: Int = -1
    var _got_password = false
    var source: com.itiancai.passport.thrift.Source = null
    var _got_source = false

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRING =>
                credentialOffset = _iprot.offsetSkipString
    
                _got_credential = true
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'credential' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRING =>
                passwordOffset = _iprot.offsetSkipString
    
                _got_password = true
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'password' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
    
                source = readSourceValue(_iprot)
                _got_source = true
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'source' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_credential) throw new TProtocolException("Required field 'credential' was not found in serialized data for struct UserLogin")
    if (!_got_password) throw new TProtocolException("Required field 'password' was not found in serialized data for struct UserLogin")
    if (!_got_source) throw new TProtocolException("Required field 'source' was not found in serialized data for struct UserLogin")
    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      credentialOffset,
      passwordOffset,
      source,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): UserLogin =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[this] def eagerDecode(_iprot: TProtocol): UserLogin = {
    var credential: String = null
    var _got_credential = false
    var password: String = null
    var _got_password = false
    var source: com.itiancai.passport.thrift.Source = null
    var _got_source = false
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRING =>
                credential = readCredentialValue(_iprot)
                _got_credential = true
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'credential' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRING =>
                password = readPasswordValue(_iprot)
                _got_password = true
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'password' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
                source = readSourceValue(_iprot)
                _got_source = true
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'source' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_credential) throw new TProtocolException("Required field 'credential' was not found in serialized data for struct UserLogin")
    if (!_got_password) throw new TProtocolException("Required field 'password' was not found in serialized data for struct UserLogin")
    if (!_got_source) throw new TProtocolException("Required field 'source' was not found in serialized data for struct UserLogin")
    new Immutable(
      credential,
      password,
      source,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    credential: String,
    password: String,
    source: com.itiancai.passport.thrift.Source
  ): UserLogin =
    new Immutable(
      credential,
      password,
      source
    )

  def unapply(_item: UserLogin): _root_.scala.Option[scala.Product3[String, String, com.itiancai.passport.thrift.Source]] = _root_.scala.Some(_item)


  @inline private def readCredentialValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeCredentialField(credential_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(CredentialField)
    writeCredentialValue(credential_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeCredentialValue(credential_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(credential_item)
  }

  @inline private def readPasswordValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writePasswordField(password_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(PasswordField)
    writePasswordValue(password_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writePasswordValue(password_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(password_item)
  }

  @inline private def readSourceValue(_iprot: TProtocol): com.itiancai.passport.thrift.Source = {
    com.itiancai.passport.thrift.Source.getOrUnknown(_iprot.readI32())
  }

  @inline private def writeSourceField(source_item: com.itiancai.passport.thrift.Source, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(SourceFieldI32)
    writeSourceValue(source_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeSourceValue(source_item: com.itiancai.passport.thrift.Source, _oprot: TProtocol): Unit = {
    _oprot.writeI32(source_item.value)
  }


  object Immutable extends ThriftStructCodec3[UserLogin] {
    override def encode(_item: UserLogin, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): UserLogin = UserLogin.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[UserLogin] = UserLogin.metaData
  }

  /**
   * The default read-only implementation of UserLogin.  You typically should not need to
   * directly reference this class; instead, use the UserLogin.apply method to construct
   * new instances.
   */
  class Immutable(
      val credential: String,
      val password: String,
      val source: com.itiancai.passport.thrift.Source,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends UserLogin {
    def this(
      credential: String,
      password: String,
      source: com.itiancai.passport.thrift.Source
    ) = this(
      credential,
      password,
      source,
      Map.empty
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      credentialOffset: Int,
      passwordOffset: Int,
      val source: com.itiancai.passport.thrift.Source,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends UserLogin {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }

    lazy val credential: String =
      if (credentialOffset == -1)
        null
      else {
        _proto.decodeString(_buf, credentialOffset)
      }
    lazy val password: String =
      if (passwordOffset == -1)
        null
      else {
        _proto.decodeString(_buf, passwordOffset)
      }

    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide signifigant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the UserLogin trait with additional state or
   * behavior and implement the read-only methods from UserLogin using an underlying
   * instance.
   */
  trait Proxy extends UserLogin {
    protected def _underlying_UserLogin: UserLogin
    override def credential: String = _underlying_UserLogin.credential
    override def password: String = _underlying_UserLogin.password
    override def source: com.itiancai.passport.thrift.Source = _underlying_UserLogin.source
    override def _passthroughFields = _underlying_UserLogin._passthroughFields
  }
}

trait UserLogin
  extends ThriftStruct
  with scala.Product3[String, String, com.itiancai.passport.thrift.Source]
  with java.io.Serializable
{
  import UserLogin._

  def credential: String
  def password: String
  def source: com.itiancai.passport.thrift.Source

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = credential
  def _2 = password
  def _3 = source


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (credential ne null) {
                writeCredentialValue(credential, _oprot)
                _root_.scala.Some(UserLogin.CredentialField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (password ne null) {
                writePasswordValue(password, _oprot)
                _root_.scala.Some(UserLogin.PasswordField)
              } else {
                _root_.scala.None
              }
            case 3 =>
              if (source ne null) {
                writeSourceValue(source, _oprot)
                _root_.scala.Some(UserLogin.SourceField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
            _root_.scala.Some(TFieldBlob(_field, _data))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): UserLogin = {
    var credential: String = this.credential
    var password: String = this.password
    var source: com.itiancai.passport.thrift.Source = this.source
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        credential = readCredentialValue(_blob.read)
      case 2 =>
        password = readPasswordValue(_blob.read)
      case 3 =>
        source = readSourceValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      credential,
      password,
      source,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): UserLogin = {
    var credential: String = this.credential
    var password: String = this.password
    var source: com.itiancai.passport.thrift.Source = this.source

    _fieldId match {
      case 1 =>
        credential = null
      case 2 =>
        password = null
      case 3 =>
        source = null
      case _ =>
    }
    new Immutable(
      credential,
      password,
      source,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetCredential: UserLogin = unsetField(1)

  def unsetPassword: UserLogin = unsetField(2)

  def unsetSource: UserLogin = unsetField(3)


  override def write(_oprot: TProtocol): Unit = {
    UserLogin.validate(this)
    _oprot.writeStructBegin(Struct)
    if (credential ne null) writeCredentialField(credential, _oprot)
    if (password ne null) writePasswordField(password, _oprot)
    if (source ne null) writeSourceField(source, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    credential: String = this.credential,
    password: String = this.password,
    source: com.itiancai.passport.thrift.Source = this.source,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): UserLogin =
    new Immutable(
      credential,
      password,
      source,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[UserLogin]

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[UserLogin]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 3

  override def productElement(n: Int): Any = n match {
    case 0 => this.credential
    case 1 => this.password
    case 2 => this.source
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "UserLogin"
}