/**
 * Generated by Scrooge
 *   version: 4.1.0
 *   rev: 87b84f89477a4737c8d57580a1e8bdaeac529b19
 *   built at: 20150928-114741
 */
package com.itiancai.passport.thrift

import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob, ThriftException, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo,
  ThriftStructMetaData, ThriftUtil}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import java.util.Arrays
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}

/**
* 返回结果信息
**/
object PassportResult extends ThriftStructCodec3[PassportResult] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("PassportResult")
  val ErrCodeField = new TField("err_code", TType.STRING, 1)
  val ErrCodeFieldManifest = implicitly[Manifest[String]]
  val ErrMsgField = new TField("err_msg", TType.STRING, 2)
  val ErrMsgFieldManifest = implicitly[Manifest[String]]
  val UserField = new TField("user", TType.STRUCT, 3)
  val UserFieldManifest = implicitly[Manifest[com.itiancai.passport.thrift.User]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      ErrCodeField,
      false,
      true,
      ErrCodeFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      ErrMsgField,
      false,
      true,
      ErrMsgFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      UserField,
      true,
      false,
      UserFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: PassportResult): Unit = {
    if (_item.errCode == null) throw new TProtocolException("Required field errCode cannot be null")
    if (_item.errMsg == null) throw new TProtocolException("Required field errMsg cannot be null")
  }

  def withoutPassthroughFields(original: PassportResult): PassportResult =
    new Immutable(
      errCode =
        {
          val field = original.errCode
          field
        },
      errMsg =
        {
          val field = original.errMsg
          field
        },
      user =
        {
          val field = original.user
          field.map { field =>
            com.itiancai.passport.thrift.User.withoutPassthroughFields(field)
          }
        }
    )

  override def encode(_item: PassportResult, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }

  private[this] def lazyDecode(_iprot: LazyTProtocol): PassportResult = {

    var err_codeOffset: Int = -1
    var _got_errCode = false
    var err_msgOffset: Int = -1
    var _got_errMsg = false
    var user: Option[com.itiancai.passport.thrift.User] = None

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRING =>
                err_codeOffset = _iprot.offsetSkipString
    
                _got_errCode = true
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'errCode' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRING =>
                err_msgOffset = _iprot.offsetSkipString
    
                _got_errMsg = true
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'errMsg' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.STRUCT =>
    
                user = Some(readUserValue(_iprot))
              case _actualType =>
                val _expectedType = TType.STRUCT
                throw new TProtocolException(
                  "Received wrong type for field 'user' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_errCode) throw new TProtocolException("Required field 'errCode' was not found in serialized data for struct PassportResult")
    if (!_got_errMsg) throw new TProtocolException("Required field 'errMsg' was not found in serialized data for struct PassportResult")
    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      err_codeOffset,
      err_msgOffset,
      user,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): PassportResult =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[this] def eagerDecode(_iprot: TProtocol): PassportResult = {
    var errCode: String = null
    var _got_errCode = false
    var errMsg: String = null
    var _got_errMsg = false
    var user: _root_.scala.Option[com.itiancai.passport.thrift.User] = _root_.scala.None
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRING =>
                errCode = readErrCodeValue(_iprot)
                _got_errCode = true
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'errCode' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRING =>
                errMsg = readErrMsgValue(_iprot)
                _got_errMsg = true
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'errMsg' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.STRUCT =>
                user = _root_.scala.Some(readUserValue(_iprot))
              case _actualType =>
                val _expectedType = TType.STRUCT
                throw new TProtocolException(
                  "Received wrong type for field 'user' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_errCode) throw new TProtocolException("Required field 'errCode' was not found in serialized data for struct PassportResult")
    if (!_got_errMsg) throw new TProtocolException("Required field 'errMsg' was not found in serialized data for struct PassportResult")
    new Immutable(
      errCode,
      errMsg,
      user,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    errCode: String,
    errMsg: String,
    user: _root_.scala.Option[com.itiancai.passport.thrift.User] = _root_.scala.None
  ): PassportResult =
    new Immutable(
      errCode,
      errMsg,
      user
    )

  def unapply(_item: PassportResult): _root_.scala.Option[scala.Product3[String, String, Option[com.itiancai.passport.thrift.User]]] = _root_.scala.Some(_item)


  @inline private def readErrCodeValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeErrCodeField(errCode_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(ErrCodeField)
    writeErrCodeValue(errCode_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeErrCodeValue(errCode_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(errCode_item)
  }

  @inline private def readErrMsgValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeErrMsgField(errMsg_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(ErrMsgField)
    writeErrMsgValue(errMsg_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeErrMsgValue(errMsg_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(errMsg_item)
  }

  @inline private def readUserValue(_iprot: TProtocol): com.itiancai.passport.thrift.User = {
    com.itiancai.passport.thrift.User.decode(_iprot)
  }

  @inline private def writeUserField(user_item: com.itiancai.passport.thrift.User, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(UserField)
    writeUserValue(user_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeUserValue(user_item: com.itiancai.passport.thrift.User, _oprot: TProtocol): Unit = {
    user_item.write(_oprot)
  }


  object Immutable extends ThriftStructCodec3[PassportResult] {
    override def encode(_item: PassportResult, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): PassportResult = PassportResult.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[PassportResult] = PassportResult.metaData
  }

  /**
   * The default read-only implementation of PassportResult.  You typically should not need to
   * directly reference this class; instead, use the PassportResult.apply method to construct
   * new instances.
   */
  class Immutable(
      val errCode: String,
      val errMsg: String,
      val user: _root_.scala.Option[com.itiancai.passport.thrift.User],
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends PassportResult {
    def this(
      errCode: String,
      errMsg: String,
      user: _root_.scala.Option[com.itiancai.passport.thrift.User] = _root_.scala.None
    ) = this(
      errCode,
      errMsg,
      user,
      Map.empty
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      err_codeOffset: Int,
      err_msgOffset: Int,
      val user: _root_.scala.Option[com.itiancai.passport.thrift.User],
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends PassportResult {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }

    lazy val errCode: String =
      if (err_codeOffset == -1)
        null
      else {
        _proto.decodeString(_buf, err_codeOffset)
      }
    lazy val errMsg: String =
      if (err_msgOffset == -1)
        null
      else {
        _proto.decodeString(_buf, err_msgOffset)
      }

    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide signifigant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the PassportResult trait with additional state or
   * behavior and implement the read-only methods from PassportResult using an underlying
   * instance.
   */
  trait Proxy extends PassportResult {
    protected def _underlying_PassportResult: PassportResult
    override def errCode: String = _underlying_PassportResult.errCode
    override def errMsg: String = _underlying_PassportResult.errMsg
    override def user: _root_.scala.Option[com.itiancai.passport.thrift.User] = _underlying_PassportResult.user
    override def _passthroughFields = _underlying_PassportResult._passthroughFields
  }
}

trait PassportResult
  extends ThriftStruct
  with scala.Product3[String, String, Option[com.itiancai.passport.thrift.User]]
  with java.io.Serializable
{
  import PassportResult._

  def errCode: String
  def errMsg: String
  def user: _root_.scala.Option[com.itiancai.passport.thrift.User]

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = errCode
  def _2 = errMsg
  def _3 = user


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (errCode ne null) {
                writeErrCodeValue(errCode, _oprot)
                _root_.scala.Some(PassportResult.ErrCodeField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (errMsg ne null) {
                writeErrMsgValue(errMsg, _oprot)
                _root_.scala.Some(PassportResult.ErrMsgField)
              } else {
                _root_.scala.None
              }
            case 3 =>
              if (user.isDefined) {
                writeUserValue(user.get, _oprot)
                _root_.scala.Some(PassportResult.UserField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
            _root_.scala.Some(TFieldBlob(_field, _data))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): PassportResult = {
    var errCode: String = this.errCode
    var errMsg: String = this.errMsg
    var user: _root_.scala.Option[com.itiancai.passport.thrift.User] = this.user
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        errCode = readErrCodeValue(_blob.read)
      case 2 =>
        errMsg = readErrMsgValue(_blob.read)
      case 3 =>
        user = _root_.scala.Some(readUserValue(_blob.read))
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      errCode,
      errMsg,
      user,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): PassportResult = {
    var errCode: String = this.errCode
    var errMsg: String = this.errMsg
    var user: _root_.scala.Option[com.itiancai.passport.thrift.User] = this.user

    _fieldId match {
      case 1 =>
        errCode = null
      case 2 =>
        errMsg = null
      case 3 =>
        user = _root_.scala.None
      case _ =>
    }
    new Immutable(
      errCode,
      errMsg,
      user,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetErrCode: PassportResult = unsetField(1)

  def unsetErrMsg: PassportResult = unsetField(2)

  def unsetUser: PassportResult = unsetField(3)


  override def write(_oprot: TProtocol): Unit = {
    PassportResult.validate(this)
    _oprot.writeStructBegin(Struct)
    if (errCode ne null) writeErrCodeField(errCode, _oprot)
    if (errMsg ne null) writeErrMsgField(errMsg, _oprot)
    if (user.isDefined) writeUserField(user.get, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    errCode: String = this.errCode,
    errMsg: String = this.errMsg,
    user: _root_.scala.Option[com.itiancai.passport.thrift.User] = this.user,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): PassportResult =
    new Immutable(
      errCode,
      errMsg,
      user,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[PassportResult]

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[PassportResult]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 3

  override def productElement(n: Int): Any = n match {
    case 0 => this.errCode
    case 1 => this.errMsg
    case 2 => this.user
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "PassportResult"
}