/**
 * Generated by Scrooge
 *   version: 4.1.0
 *   rev: 87b84f89477a4737c8d57580a1e8bdaeac529b19
 *   built at: 20150928-114741
 */
package com.itiancai.passport.thrift

import java.util.Arrays

import com.twitter.scrooge.{LazyTProtocol, TFieldBlob, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo, ThriftStructMetaData}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.TMemoryBuffer

import scala.collection.Map
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.{ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer, Builder, HashMap => mutable$HashMap, HashSet => mutable$HashSet}

/**
* 用户信息
**/
object User extends ThriftStructCodec3[User] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("User")
  val MobileField = new TField("mobile", TType.STRING, 1)
  val MobileFieldManifest = implicitly[Manifest[String]]
  val PasswordField = new TField("password", TType.STRING, 2)
  val PasswordFieldManifest = implicitly[Manifest[String]]
  val SourceField = new TField("source", TType.ENUM, 3)
  val SourceFieldI32 = new TField("source", TType.I32, 3)
  val SourceFieldManifest = implicitly[Manifest[com.itiancai.passport.thrift.Source]]
  val LoginNameField = new TField("loginName", TType.STRING, 4)
  val LoginNameFieldManifest = implicitly[Manifest[String]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      MobileField,
      false,
      true,
      MobileFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      PasswordField,
      false,
      true,
      PasswordFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      SourceField,
      false,
      true,
      SourceFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      LoginNameField,
      true,
      false,
      LoginNameFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: User): Unit = {
    if (_item.mobile == null) throw new TProtocolException("Required field mobile cannot be null")
    if (_item.password == null) throw new TProtocolException("Required field password cannot be null")
    if (_item.source == null) throw new TProtocolException("Required field source cannot be null")
  }

  def withoutPassthroughFields(original: User): User =
    new Immutable(
      mobile =
        {
          val field = original.mobile
          field
        },
      password =
        {
          val field = original.password
          field
        },
      source =
        {
          val field = original.source
          field
        },
      loginName =
        {
          val field = original.loginName
          field.map { field =>
            field
          }
        }
    )

  override def encode(_item: User, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }

  private[this] def lazyDecode(_iprot: LazyTProtocol): User = {

    var mobileOffset: Int = -1
    var _got_mobile = false
    var passwordOffset: Int = -1
    var _got_password = false
    var source: com.itiancai.passport.thrift.Source = null
    var _got_source = false
    var loginNameOffset: Int = -1

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRING =>
                mobileOffset = _iprot.offsetSkipString
    
                _got_mobile = true
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'mobile' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRING =>
                passwordOffset = _iprot.offsetSkipString
    
                _got_password = true
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'password' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
    
                source = readSourceValue(_iprot)
                _got_source = true
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'source' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 4 =>
            _field.`type` match {
              case TType.STRING =>
                loginNameOffset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'loginName' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_mobile) throw new TProtocolException("Required field 'mobile' was not found in serialized data for struct User")
    if (!_got_password) throw new TProtocolException("Required field 'password' was not found in serialized data for struct User")
    if (!_got_source) throw new TProtocolException("Required field 'source' was not found in serialized data for struct User")
    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      mobileOffset,
      passwordOffset,
      source,
      loginNameOffset,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): User =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[this] def eagerDecode(_iprot: TProtocol): User = {
    var mobile: String = null
    var _got_mobile = false
    var password: String = null
    var _got_password = false
    var source: com.itiancai.passport.thrift.Source = null
    var _got_source = false
    var loginName: _root_.scala.Option[String] = _root_.scala.None
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRING =>
                mobile = readMobileValue(_iprot)
                _got_mobile = true
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'mobile' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRING =>
                password = readPasswordValue(_iprot)
                _got_password = true
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'password' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
                source = readSourceValue(_iprot)
                _got_source = true
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'source' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 4 =>
            _field.`type` match {
              case TType.STRING =>
                loginName = _root_.scala.Some(readLoginNameValue(_iprot))
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'loginName' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    if (!_got_mobile) throw new TProtocolException("Required field 'mobile' was not found in serialized data for struct User")
    if (!_got_password) throw new TProtocolException("Required field 'password' was not found in serialized data for struct User")
    if (!_got_source) throw new TProtocolException("Required field 'source' was not found in serialized data for struct User")
    new Immutable(
      mobile,
      password,
      source,
      loginName,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    mobile: String,
    password: String,
    source: com.itiancai.passport.thrift.Source,
    loginName: _root_.scala.Option[String] = _root_.scala.None
  ): User =
    new Immutable(
      mobile,
      password,
      source,
      loginName
    )

  def unapply(_item: User): _root_.scala.Option[scala.Product4[String, String, com.itiancai.passport.thrift.Source, Option[String]]] = _root_.scala.Some(_item)


  @inline private def readMobileValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeMobileField(mobile_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(MobileField)
    writeMobileValue(mobile_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeMobileValue(mobile_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(mobile_item)
  }

  @inline private def readPasswordValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writePasswordField(password_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(PasswordField)
    writePasswordValue(password_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writePasswordValue(password_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(password_item)
  }

  @inline private def readSourceValue(_iprot: TProtocol): com.itiancai.passport.thrift.Source = {
    com.itiancai.passport.thrift.Source.getOrUnknown(_iprot.readI32())
  }

  @inline private def writeSourceField(source_item: com.itiancai.passport.thrift.Source, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(SourceFieldI32)
    writeSourceValue(source_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeSourceValue(source_item: com.itiancai.passport.thrift.Source, _oprot: TProtocol): Unit = {
    _oprot.writeI32(source_item.value)
  }

  @inline private def readLoginNameValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeLoginNameField(loginName_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(LoginNameField)
    writeLoginNameValue(loginName_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeLoginNameValue(loginName_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(loginName_item)
  }


  object Immutable extends ThriftStructCodec3[User] {
    override def encode(_item: User, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): User = User.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[User] = User.metaData
  }

  /**
   * The default read-only implementation of User.  You typically should not need to
   * directly reference this class; instead, use the User.apply method to construct
   * new instances.
   */
  class Immutable(
      val mobile: String,
      val password: String,
      val source: com.itiancai.passport.thrift.Source,
      val loginName: _root_.scala.Option[String],
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends User {
    def this(
      mobile: String,
      password: String,
      source: com.itiancai.passport.thrift.Source,
      loginName: _root_.scala.Option[String] = _root_.scala.None
    ) = this(
      mobile,
      password,
      source,
      loginName,
      Map.empty
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      mobileOffset: Int,
      passwordOffset: Int,
      val source: com.itiancai.passport.thrift.Source,
      loginNameOffset: Int,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends User {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }

    lazy val mobile: String =
      if (mobileOffset == -1)
        null
      else {
        _proto.decodeString(_buf, mobileOffset)
      }
    lazy val password: String =
      if (passwordOffset == -1)
        null
      else {
        _proto.decodeString(_buf, passwordOffset)
      }
    lazy val loginName: _root_.scala.Option[String] =
      if (loginNameOffset == -1)
        None
      else {
        Some(_proto.decodeString(_buf, loginNameOffset))
      }

    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide signifigant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the User trait with additional state or
   * behavior and implement the read-only methods from User using an underlying
   * instance.
   */
  trait Proxy extends User {
    protected def _underlying_User: User
    override def mobile: String = _underlying_User.mobile
    override def password: String = _underlying_User.password
    override def source: com.itiancai.passport.thrift.Source = _underlying_User.source
    override def loginName: _root_.scala.Option[String] = _underlying_User.loginName
    override def _passthroughFields = _underlying_User._passthroughFields
  }
}

trait User
  extends ThriftStruct
  with scala.Product4[String, String, com.itiancai.passport.thrift.Source, Option[String]]
  with java.io.Serializable
{
  import User._

  def mobile: String
  def password: String
  def source: com.itiancai.passport.thrift.Source
  def loginName: _root_.scala.Option[String]

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = mobile
  def _2 = password
  def _3 = source
  def _4 = loginName


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (mobile ne null) {
                writeMobileValue(mobile, _oprot)
                _root_.scala.Some(User.MobileField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (password ne null) {
                writePasswordValue(password, _oprot)
                _root_.scala.Some(User.PasswordField)
              } else {
                _root_.scala.None
              }
            case 3 =>
              if (source ne null) {
                writeSourceValue(source, _oprot)
                _root_.scala.Some(User.SourceField)
              } else {
                _root_.scala.None
              }
            case 4 =>
              if (loginName.isDefined) {
                writeLoginNameValue(loginName.get, _oprot)
                _root_.scala.Some(User.LoginNameField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
            _root_.scala.Some(TFieldBlob(_field, _data))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): User = {
    var mobile: String = this.mobile
    var password: String = this.password
    var source: com.itiancai.passport.thrift.Source = this.source
    var loginName: _root_.scala.Option[String] = this.loginName
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        mobile = readMobileValue(_blob.read)
      case 2 =>
        password = readPasswordValue(_blob.read)
      case 3 =>
        source = readSourceValue(_blob.read)
      case 4 =>
        loginName = _root_.scala.Some(readLoginNameValue(_blob.read))
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      mobile,
      password,
      source,
      loginName,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): User = {
    var mobile: String = this.mobile
    var password: String = this.password
    var source: com.itiancai.passport.thrift.Source = this.source
    var loginName: _root_.scala.Option[String] = this.loginName

    _fieldId match {
      case 1 =>
        mobile = null
      case 2 =>
        password = null
      case 3 =>
        source = null
      case 4 =>
        loginName = _root_.scala.None
      case _ =>
    }
    new Immutable(
      mobile,
      password,
      source,
      loginName,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetMobile: User = unsetField(1)

  def unsetPassword: User = unsetField(2)

  def unsetSource: User = unsetField(3)

  def unsetLoginName: User = unsetField(4)


  override def write(_oprot: TProtocol): Unit = {
    User.validate(this)
    _oprot.writeStructBegin(Struct)
    if (mobile ne null) writeMobileField(mobile, _oprot)
    if (password ne null) writePasswordField(password, _oprot)
    if (source ne null) writeSourceField(source, _oprot)
    if (loginName.isDefined) writeLoginNameField(loginName.get, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    mobile: String = this.mobile,
    password: String = this.password,
    source: com.itiancai.passport.thrift.Source = this.source,
    loginName: _root_.scala.Option[String] = this.loginName,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): User =
    new Immutable(
      mobile,
      password,
      source,
      loginName,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[User]

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[User]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 4

  override def productElement(n: Int): Any = n match {
    case 0 => this.mobile
    case 1 => this.password
    case 2 => this.source
    case 3 => this.loginName
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "User"
}